
// AUTOMATICALLY GENERATED BY CDK -- DO NOT EDIT
//
#include <cdk/ast/all.h>

#ifdef __NODE_DECLARATIONS_ONLY__

namespace fir {

class address_node;
class block_node;
class declaration_variable_node;
class evaluation_node;
class for_other_wise_node;
class function_call_node;
class function_decl_node;
class function_def_node;
class identity_node;
class if_else_node;
class if_node;
class index_node;
class indexationptr_node;
class leave_node;
class memory_reserve_node;
class nullptr_node;
class prologo_node;
class read_node;
class restart_node;
class return_node;
class size_of_node;
class while_node;
class write_node;


} // namespace fir

#else /* !defined(__NODE_DECLARATIONS_ONLY__) */

#ifndef __AUTOMATIC_fir_NODE_ALLNODES_H__
#define __AUTOMATIC_fir_NODE_ALLNODES_H__

#include "ast/address_node.h"
#include "ast/block_node.h"
#include "ast/declaration_variable_node.h"
#include "ast/evaluation_node.h"
#include "ast/for_other_wise_node.h"
#include "ast/function_call_node.h"
#include "ast/function_decl_node.h"
#include "ast/function_def_node.h"
#include "ast/identity_node.h"
#include "ast/if_else_node.h"
#include "ast/if_node.h"
#include "ast/index_node.h"
#include "ast/indexationptr_node.h"
#include "ast/leave_node.h"
#include "ast/memory_reserve_node.h"
#include "ast/nullptr_node.h"
#include "ast/prologo_node.h"
#include "ast/read_node.h"
#include "ast/restart_node.h"
#include "ast/return_node.h"
#include "ast/size_of_node.h"
#include "ast/while_node.h"
#include "ast/write_node.h"


#endif /* !defined(__AUTOMATIC_fir_NODE_ALLNODES_H__) */

#endif /* !defined(__NODE_DECLARATIONS_ONLY__) */

